### ISSUE TITLE
make scan filtering a method of SCMzml

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/ScanCentricPeakCharacterization#25]
Right now scan filtering is done as a separate function like this:

```
sc_mzml = filter_remove_outlier_scans(sc_mzml)
```

But **all** of our other functions are done like this:

```
sc_mzml$method_call()
```

So this should be changed to make it more consistent with everything else.

**Comment by rmflight** [comment]
OK, so there is an issue here.

The current implementation, `generate_scan_outlier_filter()` is a standalone function (see code [here](https://github.com/MoseleyBioinformaticsLab/ScanCentricPeakCharacterization/blob/scan_filtering_method/R/generators.R#L29)), **not** a method of `SCMzml`.

This means that any functions the generator makes, don't have internal access to the the `self` object that methods of the `SCMzml` object do.

I see a few different ways to go about fixing this.

1. Provide a class generator that creates a new class that `set`s the  scan filtering function, and then creates the instance of the class.
    * This feels cumbersome and will be hard to debug when things go sideways.
2. Add a few more methods to the `SCMzml` class, that include `add_filter` and `filter....` and `filter_function`. The `add_filter` puts the generated function in the right spot, `filter...` has access to `self`, and calls `filter_function` properly.
    * This adds **a lot** more slots to the object class, and starts to be more opaque, I think.
3. Make `generate_scan_outlier_filter` a method of the `SCMzml` object itself, and it puts the  generated function in the right place, and sets it up to be called properly by the more general `filter...` function.
    * I like this option the best I think. The generator is attached to the class object itself, and knows where to put everything so the end function gets called properly.

**Comment by hunter-moseley** [comment]
The 3rd option should be easiest to implement and maintain, but may limit
the range of filters possible.

The 2nd option should be more flexible, but is harder to implement and
maintain.

3rd option is likely the best option in this situation, but could be later
reimplemented closer to option 2.

**Comment by rmflight** [comment]
One way I could see allowing full flexibility, would be that if the
generator is passed a function, it just passes the function through, and
sets it up properly, instead of generating it's own.

At least, based on what I know of R, I should be able to do that, so it can
handle the ultimate customized situation, but the API for setting a
function is consistent.

**Comment by rmflight** [comment]
OK, as of [this addition](https://github.com/MoseleyBioinformaticsLab/ScanCentricPeakCharacterization/blob/cb2767dcf18384150479cee5381fe3d60ba60cc5/R/SCMzml.R#L322), it works!

But having done that for filtering, I've realized I should do the same for **single frequency model selection**. At the very least, the generator should put on the builtin version, or a supplied alternative. But that is a task for another chunk of time.
